version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "03:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "actions/checkout"
        versions: ["<3.0.0"]
