github: davidanderson01
patreon: davidanderson01
open_collective: davidanderson01
ko_fi: davidanderson75987
tidelift: your-tidelift-project-id
community_bridge: your-community-bridge-project-id
liberapay: your-liberapay-username
issuehunt: your-issuehunt-username
otechie: your-otechie-username
custom: 
  - https://your-custom-donation-link.com
